export { default as OrderCancelledTemplate } from './orderCancelled';
export { default as OrderConfirmationTemplate } from './orderConfirmation';
export { default as OrderDeliveredTemplate } from './orderDelivered';
export { default as OrderShippedTemplate } from './orderShipped';
export { default as PasswordResetTemplate } from './passwordReset';
export { default as ReturnAcceptedTemplate } from './returnAccepted';
export { default as ReturnCompletedTemplate } from './returnCompleted';
export { default as ReturnDeniedTemplate } from './returnDenied';
export { default as WelcomeEmailTemplate } from './welcome';
